### ISSUE TITLE
Not add version So not get any data. Please update like this 

### ISSUE THREAD

**Issue by ppatelwve** [adesigns/nppes-api#3]
/**
     * Search for a single provider by NPI Number
     *
     * @param $number
     * @return Provider|null Returns a Provider if one is found by the number, otherwise null
     */
    public function searchByNumber($number,$version='2.1')
    {
        $apiRequest = $this->apiClient->get("", ['number' => $number, 'version' => $version]);

        $response = $this->handleResponse($apiRequest);

        if ($response->getResultCount() == 1) {
            return $response->getResults()[0];
        }

        return null;
    }

File path: vendor\adesigns\nppes-api\src\AlbanyDesigns\NPPESApi\NPPESApi.php

**Comment by michaelyudin** [comment]
Can you please submit a pull request for this issue?

**Comment by mikeyudin** [comment]
Fixed in #4
